In [33]:
import numpy as np

In [34]:
import numpy as np

# 假设有数据 X 和标签 y
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])

# 保存为 npz 文件
np.savez('data.npz', features=X, a=y)

# 读取时使用文件中的名称
data = np.load('data.npz')
X_loaded = data['features']
y_loaded = data['a']

print(X_loaded)
print(y_loaded)


[[1 2]
 [3 4]
 [5 6]]
[0 1 0]


In [35]:
data.files

['features', 'a']

In [36]:
'./data.npz'.split('.')

['', '/data', 'npz']

In [37]:
from utils.data_template import DataLoader
my_data = DataLoader('./data.npz')

In [41]:
len(my_data)

2

In [4]:
import numpy as np

np.hstack((np.array([1, 2, 3]).reshape(-1, 1), np.array([4, 5, 6]).reshape(-1, 1)))

array([[1, 4],
       [2, 5],
       [3, 6]])